### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, bool given in /var/www/FreshRSS/extensions/freshrss-image-cache-plugin-0.4/extension.php:77

### ISSUE THREAD

**Issue by Whichbfj28** [Victrid/freshrss-image-cache-plugin#7]
```
PHP Fatal error:  Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, bool given in /var/www/FreshRSS/extensions/freshrss-image-cache-plugin-0.4/extension.php:77
Stack trace:
#0 /var/www/FreshRSS/extensions/freshrss-image-cache-plugin-0.4/extension.php(77): json_decode()
#1 /var/www/FreshRSS/extensions/freshrss-image-cache-plugin-0.4/extension.php(84): ImageCacheExtension::curlPostRequest()
#2 /var/www/FreshRSS/extensions/freshrss-image-cache-plugin-0.4/extension.php(112): ImageCacheExtension::send_proactive_cache_request()
#3 /var/www/FreshRSS/extensions/freshrss-image-cache-plugin-0.4/extension.php(164): ImageCacheExtension::cache_images()
#4 /var/www/FreshRSS/lib/Minz/ExtensionManager.php(374): ImageCacheExtension::image_upload_hook()
#5 /var/www/FreshRSS/lib/Minz/ExtensionManager.php(344): Minz_ExtensionManager::callOneToOne()
#6 /var/www/FreshRSS/app/Controllers/feedController.php(522): Minz_ExtensionManager::callHook()
#7 /var/www/FreshRSS/app/Controllers/feedController.php(737): FreshRSS_feed_Controller::actualizeFeeds()
#8 /var/www/FreshRSS/lib/Minz/Dispatcher.php(120): FreshRSS_feed_Controller->actualizeAction()
#9 /var/www/FreshRSS/lib/Minz/Dispatcher.php(49): Minz_Dispatcher->launchAction()
#10 /var/www/FreshRSS/lib/Minz/FrontController.php(61): Minz_Dispatcher->run()

```

When updating the feed of freshrss, these logs appear

This problem occurs when updating the feed source https://rsshub.app/jiemian/lists/2?filterout_author=%E7%95%8C%E9%9D%A2%E5%BF%AB%E6%8A%A5

When this problem occurs. It will lock up the update. Causing other feed sources to fail to update.

**Comment by Whichbfj28** [comment]
Already searched the help file at freshrss. It should be that the extension is throwing an error that stops the update
